# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versions',
            old_name='product',
            new_name='versionName',
        ),
    ]
