# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180226_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versions',
            name='versionName',
            field=models.CharField(max_length=250),
        ),
    ]
