# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180226_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productLogo',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
