# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_product_productlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
